name: Build and deploy code

on: [push, pull_request]

jobs:
  job-1:
    environment:
      name: env1
    env:
      DB_HOSTNAME: ${{secrets.DB_HOSTNAME}}
      DB_PASSWORD: ${{secrets.DB_PASSWORD}}
      DB_USERNAME: ${{secrets.DB_USERNAME}}
      DB_URL: ${{secrets.DB_URL}}
      DB_PORT: ${{secrets.DB_PORT}}
      DB_NAME: ${{secrets.DB_NAME}}
      SECRET: ${{secrets.SECRET}}
      ALGORITHM: ${{secrets.ALGORITHM}}
      ACCESS_TOKEN_EXPIRY_MINUTES: ${{secrets.ACCESS_TOKEN_EXPIRY_MINUTES}}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          POSTGRES_DB: ${{secrets.DATABASE_NAME}}_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    runs-on: ubuntu-22.04
    steps:
      - name: a description like checking code
        uses: actions/checkout@v3
      - name: say cheeze
        run: echo "cheeze"
      - name: installing python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: upgrade pip
        run: python -m pip install --upgrade pip
      - name: install dependencies
        run: pip install -r requirements.txt
      - name: testing
        run: |
          pip install pytest
          pytest -v
